"""Render a clean, human-readable Markdown summary of the current forecast.

``write_report`` reads whatever of the live prediction / simulation / metrics
outputs currently exist and writes a single tidy ``PREDICTIONS.md`` at the repo
root. It is invoked automatically at the end of ``worldcup predict`` and
``worldcup simulate`` (and on demand via ``worldcup report``), so the file always
reflects the latest run on the latest data without any manual step.
"""
from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

# Tournament-probability columns mapped to friendly headers, widest round first.
_STAGE_HEADERS = [
    ("champion", "Champion"),
    ("reach_final", "Final"),
    ("reach_semi_final", "Semi"),
    ("reach_quarter_final", "Quarter"),
    ("reach_round_of_16", "R16"),
    ("reach_round_of_32", "R32"),
]


def _pct(value: float, decimals: int = 1) -> str:
    try:
        return f"{float(value) * 100:.{decimals}f}%"
    except (TypeError, ValueError):
        return "—"


def _read_csv(path: Path) -> pd.DataFrame | None:
    if path.is_file() and path.stat().st_size:
        try:
            return pd.read_csv(path)
        except (OSError, pd.errors.ParserError, pd.errors.EmptyDataError):
            return None
    return None


def _header(config: dict, root: Path, results_through: str | None) -> list[str]:
    model_through = commit = None
    metrics_path = root / config["paths"].get("metrics", "")
    if metrics_path.is_file():
        try:
            model_through = json.loads(metrics_path.read_text()).get(
                "training_through"
            )
        except (json.JSONDecodeError, OSError):
            model_through = None
    log_index = (
        root
        / config["paths"].get("predictions_log", "predictions_log")
        / "index.jsonl"
    )
    if log_index.is_file():
        for line in reversed(log_index.read_text().splitlines()):
            if line.strip():
                try:
                    commit = json.loads(line).get("git_commit")
                except json.JSONDecodeError:
                    commit = None
                break
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    facts = [f"generated {generated}"]
    if results_through:
        facts.append(f"data through {results_through}")
    if model_through:
        facts.append(f"model trained through {model_through}")
    if commit:
        facts.append(f"commit `{commit}`")
    return [
        "# World Cup 2026 — Model Predictions",
        "",
        "_" + " · ".join(facts) + "_",
        "",
        (
            "Auto-generated by `worldcup predict` / `worldcup simulate`. "
            "Every rerun on new data overwrites this file."
        ),
        "",
    ]


def _tournament_section(simulation: pd.DataFrame) -> list[str]:
    present = [
        (column, label)
        for column, label in _STAGE_HEADERS
        if column in simulation.columns
    ]
    if "team" not in simulation.columns or not present:
        return []
    ordered = simulation.sort_values(
        present[0][0], ascending=False
    ).reset_index(drop=True)
    headers = ["Team", *[label for _, label in present]]
    lines = [
        "## Title & advancement probabilities",
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "---|" + "|".join(["---:"] * len(present)) + "|",
    ]
    for _, row in ordered.iterrows():
        cells = [str(row["team"])]
        cells += [_pct(row[column]) for column, _ in present]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    return lines


def _match_section(predictions: pd.DataFrame) -> list[str]:
    required = {"home_team", "away_team", "home_win", "draw", "away_win"}
    if not required.issubset(predictions.columns):
        return []
    frame = predictions.copy()
    if "date" in frame:
        frame["_label"] = pd.to_datetime(frame["date"]).dt.strftime("%b %d")
    else:
        frame["_label"] = ""
    lines = [
        "## Group-stage match predictions",
        "",
        "Win / Draw / Win is from the home team's perspective. xG is expected "
        "goals; O2.5 is over 2.5 total goals; BTTS is both teams to score.",
        "",
        "| Date | Grp | Match | Home / Draw / Away | Likely | xG | O2.5 | BTTS |",
        "|---|---|---|---|---|---|---:|---:|",
    ]
    for _, row in frame.iterrows():
        match = f"{row['home_team']} vs {row['away_team']}"
        wdl = (
            f"{_pct(row['home_win'], 0)} / "
            f"{_pct(row['draw'], 0)} / "
            f"{_pct(row['away_win'], 0)}"
        )
        likely = str(row.get("most_likely_score", "")).replace(" ", "")
        xg = "—"
        if "expected_home_goals" in row and "expected_away_goals" in row:
            xg = (
                f"{float(row['expected_home_goals']):.1f}–"
                f"{float(row['expected_away_goals']):.1f}"
            )
        over = _pct(row["over_2_5"], 0) if "over_2_5" in row else "—"
        btts = (
            _pct(row["both_teams_to_score"], 0)
            if "both_teams_to_score" in row
            else "—"
        )
        cells = [
            str(row["_label"]),
            str(row.get("group", "")),
            match,
            wdl,
            likely,
            xg,
            over,
            btts,
        ]
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")
    return lines


def _model_section(root: Path, config: dict) -> list[str]:
    metrics_path = root / config["paths"].get("metrics", "")
    if not metrics_path.is_file():
        return []
    try:
        metrics = json.loads(metrics_path.read_text())
    except (json.JSONDecodeError, OSError):
        return []
    rows = [
        ("Outcome log loss", "outcome_log_loss", "elo_baseline_log_loss"),
        ("Ranked probability score", "ranked_probability_score", "elo_baseline_rps"),
        ("Brier score", "brier_score", None),
        ("Calibration error", "calibration_error", None),
    ]
    lines = [
        "## Model snapshot",
        "",
        "| Metric | Model | Elo baseline |",
        "|---|---:|---:|",
    ]
    for label, key, baseline in rows:
        if key not in metrics:
            continue
        base = (
            f"{metrics[baseline]:.4f}"
            if baseline and baseline in metrics
            else "—"
        )
        lines.append(f"| {label} | {metrics[key]:.4f} | {base} |")
    active = metrics.get("active_features")
    if active is not None:
        lines.append(f"| Active features | {len(active)} | — |")
    training = metrics.get("training_matches")
    if training is not None:
        lines.append(f"| Training matches | {training:,} | — |")
    lines.append("")
    lines.append("_Holdout metrics; lower is better. See README for the stricter "
                 "whole-tournament backtest._")
    lines.append("")
    return lines


def write_report(config: dict, results_through: str | None = None) -> Path | None:
    """Render PREDICTIONS.md from the current outputs. Returns its path."""
    root = Path(config.get("_root", "."))
    report_path = root / config["paths"].get("report", "PREDICTIONS.md")
    simulation = _read_csv(root / config["paths"].get("simulation", ""))
    predictions = _read_csv(root / config["paths"].get("predictions", ""))

    body = _header(config, root, results_through)
    if simulation is not None:
        body += _tournament_section(simulation)
    if predictions is not None:
        body += _match_section(predictions)
    body += _model_section(root, config)
    if simulation is None and predictions is None:
        body += [
            "_No predictions yet. Run `worldcup predict` and "
            "`worldcup simulate`._",
            "",
        ]

    report_path.write_text("\n".join(body).rstrip() + "\n")
    return report_path
